const menu = [
    {
        id: 1,
        name: "Double Cheeseburger wih Fries",
        category: "Lunch",
        description: "Double patties with American cheese, lettuce, tomato, ketchup and mayo",
        image: "https://thumbs.dreamstime.com/z/double-cheeseburger-lettuce-tomato-onion-melted-american-cheese-double-cheeseburger-lettuce-tomato-onion-melted-123765411.jpg",
        price: 8.99,
    }
    ,
    {
        id: 2,
        name: "Chilli Cheese Fries",
        category: "Lunch",
        description: "These chili cheese fries are crispy french fries topped with homemade beef chili and cheese cheese, then baked to melted perfection",
        image: "https://media.istockphoto.com/photos/unhealthy-messy-chili-cheese-fries-picture-id183897095?s=612x612",
        price: 5.99,
    },
    {
        id: 3,
        name: "Chicken Parm Sandwich",
        category: "Lunch",
        description: "The chicken is wonderfully tender and crispy, and topped with marinara and mozzarella for a really tasty bite!",
        image:"https://littlesunnykitchen.com/wp-content/uploads/2021/04/Chicken-Parmesan-Sandwich-8.jpg",
        price: 10.99,
    },
    {
        id: 4,
        name: "Philly Cheese Steak",
        category: "Lunch",
        description: "Tender ribeye steak, melted gooey provolone, and caramelized onions hugged by a toasted garlic butter hoagie roll. This is the classic way to make a Philly Cheesesteak sandwich!",
        image:"https://thestayathomechef.com/wp-content/uploads/2020/09/Authentic-Philly-Cheesesteak-5.jpg",
        price: 15.99,
    },
    {
        id: 5,
        name: "Steak and Shrimp Dinner",
        category: "Dinner",
        description: "Skillet garlic butter steak and shrimp is pan-seared to tender and juicy perfection and slathered in garlic herb butter.",
        image:"https://www.heinens.com/wp-content/uploads/2020/07/Steak-and-Shrimp-Skillet_1_600x700.jpg",
        price: 20.99,
    },
    {
        id: 6,
        name: "Chicken Marsala",
        category: "Dinner",
        description: "Double patties with American cheese, lettuce, tomato, and mayo",
        image:"https://www.onceuponachef.com/images/2018/01/Chicken-Marsala.jpg",
        price: 5.99,
    },
    {
        id: 7,
        name: "Lobster Dinner",
        category: "Dinner",
        description: "Double patties with American cheese, lettuce, tomato, and mayo",
        image:"https://media.istockphoto.com/photos/cooked-lobster-tails-with-lemon-dill-picture-id1025237294?k=20&m=1025237294&s=612x612&w=0&h=wnatEPshIrn4oGXyoRos41Wpa8nGA-VPskv_-gogvmQ=",
        price: 5.99,
    },
    {
        id: 8,
        name: "Chicken Salad",
        category: "Dinner",
        description: "Double patties with American cheese, lettuce, tomato, and mayo",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ-GGfKhxKu-uH1dLjK-m3jn0KEMzgHe-i1ZgiZOzVHl7mLw4BkMd2drk28skQYIKu7NY&usqp=CAU",
        price: 5.99,
    },
    {
        id: 9,
        name: "Cheese Omlette",
        category: "Breakfast",
        description: "Double patties with American cheese, lettuce, tomato, and mayo",
        image:"https://bellyfull.net/wp-content/uploads/2020/08/Omelette-blog-3.jpg",
        price: 8.99,
    },
    {
        id: 10,
        name: "Buttermilk Pancakes",
        category: "Breakfast",
        description: "Fluffy Pancakes with syrup and a side of scramble eggs",
        image:"https://i.etsystatic.com/24708295/r/il/323fde/3513312575/il_1588xN.3513312575_q4ag.jpg",
        price: 12.99,
    },
    {
        id: 11,
        name: "Bacon Egg and Cheese Sandwich",
        category: "Breakfast",
        description: "Includes crispy bacon, fried eggs, yellow American cheese, all piled onto a poppy seed sandwich roll",
        image:"https://www.sipandfeast.com/wp-content/uploads/2021/10/bacon-egg-cheese-recipe-snippet.jpg",
        price: 8.99,
    },
    {
        id: 12,
        name: "Soda",
        category: "Beverages",
        description: "Coke, Sprite, Mountain Dew",
        image:"https://www.fodors.com/wp-content/uploads/2019/03/HERO_Worlds_Best_Soda_Bundaberg_shutterstock_679079920.jpg",
        price: 2.99,
    },
    {
        id: 13,
        name: "Lemonade or Ice Tea",
        category: "Beverages",
        description: "Lemon,  Peach, Rasberry, Strawberry",
        image:"https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVtb25hZGV8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60",
        price: 2.99,
    },
];


export default menu;